config/urls.py
"""fsdviz URL Configuration
"""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from django.contrib.flatpages import views as flatpage_views
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from fsdviz.myusers.views import account_redirect

# our homepage:  TEMP!!
from fsdviz.stocking.views import PieChartMapViewLastYear
from rest_framework.documentation import include_docs_urls
from rest_framework.permissions import AllowAny


from fsdviz.common.api.views import (
    AgencyViewSet,
    SpeciesViewSet,
    JurisdictionViewSet,
    StateProvinceViewSet,
    LakeViewSet,
    ManagementUnitViewSet,
    StrainSpeciesViewSet,
    StrainAliasViewSet,
    Grid10ViewSet,
    LatLonFlagViewSet,
    MarkViewSet,
)

from fsdviz.stocking.api.views import (
    LifeStageViewSet,
    YearlingEquivalentViewSet,
    StockingMortalityViewSet,
    StockingMethodViewSet,
    StockingEventViewSet,
    CWTEventListAPIView,
)


API_TITLE = "Great Lakes Fish Stocking API"
API_DESCRIPTION = "A web API for Great Lakes Fish Stocking Database"


public_urls = [
    path("api/v1/common/lake", LakeViewSet.as_view({"get": "list"})),
    path("api/v1/common/agency", AgencyViewSet.as_view({"get": "list"})),
    path("api/v1/common/jurisdiction", JurisdictionViewSet.as_view({"get": "list"})),
    path(
        "api/v1/common/management_unit", ManagementUnitViewSet.as_view({"get": "list"})
    ),
    path("api/v1/common/state_province", StateProvinceViewSet.as_view({"get": "list"})),
    path("api/v1/common/grid10", Grid10ViewSet.as_view({"get": "list"})),
    path("api/v1/common/latlonflag", LatLonFlagViewSet.as_view({"get": "list"})),
    path("api/v1/common/mark", MarkViewSet.as_view({"get": "list"})),
    path("api/v1/common/species", SpeciesViewSet.as_view({"get": "list"})),
    path("api/v1/common/strain", StrainSpeciesViewSet.as_view({"get": "list"})),
    path("api/v1/common/strain_alias", StrainAliasViewSet.as_view({"get": "list"})),
    path("api/v1/stocking/lifestage", LifeStageViewSet.as_view({"get": "list"})),
    path(
        "api/v1/stocking/yearling_equivalent",
        YearlingEquivalentViewSet.as_view({"get": "list"}),
    ),
    path("api/v1/stocking/stocking_mortality", StockingMortalityViewSet.as_view({"get": "list"})),
    path(
        "api/v1/stocking/stocking_method",
        StockingMethodViewSet.as_view({"get": "list"}),
    ),
    path("api/v1/stocking/events", StockingEventViewSet.as_view({"get": "list"})),
    path("api/v1/stocking/get_cwt_events", CWTEventListAPIView.as_view()),
]

schema_view = get_schema_view(
    openapi.Info(
        title=API_TITLE,
        default_version="v1",
        description=API_DESCRIPTION,
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="adam.cottrill@ontario.ca"),
        license=openapi.License(name="BSD License"),
    ),
    # generate docs for all endpoint from here down:
    # patterns=urlpatterns + common_api_urls + stocking_api_urls,
    patterns=public_urls,
    public=True,
    permission_classes=(AllowAny,),
)


urlpatterns = [
    path("coregonusclupeaformis/doc/", include("django.contrib.admindocs.urls")),
    path("coregonusclupeaformis/", admin.site.urls),
    path("login/", account_redirect, name="account-redirect"),
    path("users/", include("fsdviz.myusers.urls")),
    path("users/", include("django.contrib.auth.urls")),
    path(
        "about/",
        flatpage_views.flatpage,
        {"url": "/about/"},
        name="about",
    ),
    path("pages/", include("django.contrib.flatpages.urls")),
    path("shared/", include("fsdviz.common.urls", namespace="common")),
    path("stocking/", include("fsdviz.stocking.urls", namespace="stocking")),
    path("resource_library/", include("resource_library.urls", "resource_library")),
    # path("cwt/", include("cwt.urls")),
    # API's
    path("tickets/", include(("tickets.urls", "tickets"), namespace="tickets")),
    path("api-auth/", include("rest_framework.urls")),

    path("api/v1/common/", include("fsdviz.common.api.urls", namespace="common_api")),
    path(
        "api/v1/stocking/",
        include("fsdviz.stocking.api.urls", namespace="stocking_api"),
    ),
    path("bookmarks/", include("bookmark_it.urls")),
    # =============================================
    #          API AND DOCUMENTATION
    path(
        "api/v1/public_urls/",
        schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),
    # api documentation
    re_path(
        r"^api/v1/swagger(?P<format>\.json|\.yaml)$",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "api/v1/swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("", PieChartMapViewLastYear, name="home"),
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = (
        [
            path("__debug__/", include(debug_toolbar.urls)),
        ]
        + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
        + urlpatterns
    )

fsdviz/common/urls.py
from django.urls import path

from .views import lookup_tables, spatial_lookup

app_name = "common"

urlpatterns = [
    path("spatial_lookup/", spatial_lookup, name="spatial-lookup"),
    path("lookup_tables/", lookup_tables, name="lookup-tables"),
]

fsdviz/myusers/urls.py
"""urls for our custom user app."""

from django.urls import path
from . import views

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup')
]

fsdviz/stocking/urls.py
from django.urls import path

from .views import (
    PieChartMapView,
    PieChartMapViewLastYear,
    StockingEventListView,
    StockingEventDetailView,
    StockingAnnualTotalsListView,
    find_events,
    filtered_events,
    upload_events,
    xls_events,
    edit_stocking_event,
    DataUploadEventListView,
    DataUploadEventDetailView,
    CWTListView,
    CWTSequenceDetail,
    find_cwt_events,
    filtered_cwt_events,
)

app_name = "stocking"

urlpatterns = [
    path("", PieChartMapViewLastYear, name="stocking-events"),
    path("find_events/", find_events, name="find-stocking-events"),
    path("filtered_events/", filtered_events, name="filtered-stocking-events"),
    path("events/<int:year>/", PieChartMapView.as_view(), name="stocking-events-year"),
    # the default events view will be to return the most recent year
    # for all lakes:
    path("events/", PieChartMapViewLastYear, name="stocking-events-latest-year"),
    # stocking event lists
    path(
        "events_list/",
        StockingEventListView.as_view(),
        name="stocking-event-list",
    ),
    path(
        "event_detail/<stock_id>/",
        StockingEventDetailView.as_view(),
        name="stocking-event-detail",
    ),
    path(
        "annual_totals/",
        StockingAnnualTotalsListView.as_view(),
        name="annual-totals-list",
    ),
    path("edit_event/<stock_id>/", edit_stocking_event, name="edit-stocking-event"),
    path("upload_events/", upload_events, name="upload-stocking-events"),
    path("uploaded_events/", xls_events, name="xls-events-form"),
    path(
        "data_upload_events/",
        DataUploadEventListView.as_view(),
        name="data-upload-event-list",
    ),
    path(
        "data_upload_event_detail/<slug>/",
        DataUploadEventDetailView.as_view(),
        name="data-upload-event-detail",
    ),
    path("cwts/", CWTListView.as_view(), name="cwt-list"),
    path(
        "cwt_detail/<str:cwt_number>/", CWTSequenceDetail.as_view(), name="cwt-detail"
    ),
    path("find_cwt_events/", find_cwt_events, name="find-cwt-stocking-events"),
    path(
        "filtered_cwt_events/", filtered_cwt_events, name="filtered-cwt-stocking-events"
    ),
]

fsdviz/common/models.py
"""
This file contains all of the django orm models for entities that will
be shared across both the stocking and cwt recovery applications.

"""

from colorfield.fields import ColorField
from django.contrib.gis.db import models

from markdown import markdown

# consider add range field and constraint to CWTSequence when we upgrade to Django 3.0+
# from django.contrib.postgres.constraints import ExclusionConstraint
from django.contrib.postgres.fields import IntegerRangeField
from django.core.exceptions import ValidationError
from django.core.validators import MaxValueValidator, MinValueValidator
from django.template.defaultfilters import slugify
from django.utils.translation import gettext_lazy

from .validators import validate_cwt_sequence_range


class BaseModel(models.Model):
    """A simple abstract model that all of our other models will inherit
    from to captuture when the record was created, and when it was
    modified
    """

    id = models.AutoField(primary_key=True)
    created_timestamp = models.DateTimeField(auto_now_add=True)
    modified_timestamp = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class LookupDescription(BaseModel):
    """A model to hold the descriptions for each Lookup table.  The
    paragraphs contained in the description field will be displayed on
    the lookup tables html page and be editable in the django admin.
    The description field will support markdown, and will be converted
    to html when the model is saved."""

    slug = models.CharField(
        max_length=255,
        unique=True,
        editable=False,
        help_text="This is the string referenced in the template for this model.",
    )
    model_name = models.CharField(
        max_length=255,
        unique=True,
        help_text=(
            "Plural Name of Model Instances (e.g. - Lakes). This usually "
            "matches the heading in the Lookup Tables html template."
        ),
    )
    description = models.TextField(
        default="Coming Soon....", help_text="Lookup Table Description (markdown)."
    )
    description_html = models.TextField(
        editable=False, help_text="Lookup Table Description (html)."
    )

    class Meta:
        ordering = ["model_name"]

    def __str__(self):
        """"""

        "String representation for a LookupDescription." ""
        return self.model_name

    def save(self, *args, **kwargs):
        """Update the slug and html when we save the model. The slug
        uses underscores rather than dashes so we can access them as
        dict keys in the template."""

        self.slug = slugify(self.model_name).replace("-", "_")
        self.description_html = markdown(self.description)

        super(LookupDescription, self).save(*args, **kwargs)


class Image(models.Model):
    """A model to hold images uploaded by our super-users to that they can
    be referenced in our documentation (data dictionary ect)."""

    id = models.AutoField(primary_key=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    title = models.CharField(max_length=255, unique=True)
    file = models.ImageField(upload_to="uploaded_images")

    def __str__(self):
        """String representation for an image object."""
        return f"{self.title}({self.file.url})"

    def get_absolute_url(self):
        return (self.file and self.file.url) or ""


class Agency(BaseModel):
    """
    A lookup table for agencies that either stock fish or recovery cwts.

    This table should probably be extended to include office/hatchery
    so that we can differentiate offices for agencies that have more
    than one. Keeping it simple for now.

    """

    abbrev = models.CharField(max_length=15, unique=True)
    agency_name = models.CharField(max_length=100, unique=True)
    color = ColorField(default="#FF0000")

    class Meta:
        verbose_name_plural = "Agencies"
        ordering = ["abbrev"]

    def get_by_natural_key(self, abbrev):
        """a helper method that will allow us to get agencies
        using abbrev as the key."""
        return self.get(abbrev=abbrev)

    def __str__(self):
        """String representation for a agency."""
        return "{} ({})".format(self.agency_name, self.abbrev)


class Lake(BaseModel):
    """
    A lookup table for lakes where fish were stocked, cwts either
    deployed or recovered, or where management/spatial units are located.

    """

    abbrev = models.CharField(max_length=2, unique=True)
    lake_name = models.CharField(max_length=30, unique=True)
    geom = models.MultiPolygonField(srid=4326, blank=True, null=True)
    color = ColorField(default="#FF0000")
    # geom including associated watersheds
    # geom_plus = models.MultiPolygonField(srid=4326, blank=True, null=True)

    max_lat = models.FloatField(
        "Northern-most latitude for events in this lake",
        blank=True,
        null=True,
        validators=[MinValueValidator(41.3), MaxValueValidator(49.1)],
    )

    min_lat = models.FloatField(
        "Southern-most latitude for events in this lake",
        blank=True,
        null=True,
        validators=[MinValueValidator(41.3), MaxValueValidator(49.1)],
    )

    max_lon = models.FloatField(
        "Eastern-most longitude for events in this lake",
        blank=True,
        null=True,
        validators=[MinValueValidator(-92.4), MaxValueValidator(-74.3)],
    )

    min_lon = models.FloatField(
        "Western-most longitude for events in this lake",
        blank=True,
        null=True,
        validators=[MinValueValidator(-92.4), MaxValueValidator(-74.3)],
    )

    class Meta:
        ordering = ["abbrev"]

    def __str__(self):
        """String representation for a lake."""
        return "{} ({})".format(self.lake_name, self.abbrev)

    def save(self, *args, **kwargs):
        """ """

        self.full_clean()
        super(Lake, self).save(*args, **kwargs)

    def clean(self):
        """Make sure that if the min and max lat and lon are
        populated, that they represent plausible values."""

        if self.min_lat and self.max_lat:
            if self.min_lat >= self.max_lat:
                msg = "Maximum Latitude must be greater than minimum Latitude."
                raise ValidationError(gettext_lazy(msg))

        if self.min_lon and self.max_lon:
            if self.min_lon >= self.max_lon:
                msg = "Maximum Longitude must be greater than minimum Longitude."
                raise ValidationError(gettext_lazy(msg))

    def coordinate_limits(self):
        """Return the min and max, lat and lon in the format expected
        by our template.  The same format is returned from extents -
        but it is calculated from the polygon geometry.  These are the
        hard-coded values that include events in tributaries that
        might be outside of a bounding box around the lake.

        """
        return [self.min_lon, self.min_lat, self.max_lon, self.max_lat]

    def short_name(self):
        """The name of the lake without 'Lake ..'.

        A shorter verson of the lake name to save spave when
        needed. THis may need to be turned into a property at some
        point.

        """

        return self.lake_name.replace("Lake ", "")


class StateProvince(BaseModel):
    """
    A lookup table for states or provinces where fish were stocked,
    cwts either deployed or recovered, or where management/spatial
    units are located.

    """

    COUNTRIES = (("USA", "U.S.A."), ("CAN", "Canada"))

    abbrev = models.CharField(max_length=5, unique=True)
    name = models.CharField(max_length=30, unique=True)
    description = models.CharField(max_length=300)
    country = models.CharField(max_length=3, choices=COUNTRIES)
    color = ColorField(default="#FF0000")

    class Meta:
        ordering = ["abbrev"]

    def __str__(self):
        """String representation for a State."""
        return "{} ({})".format(self.name, self.abbrev)


class Jurisdiction(BaseModel):
    """A lookup table for geographic extents of a state or province
    within a lake.  This will be important for managers to find the
    waters that they are responsible for.

    For many states, there will only be a single juristiction
    (e.g. the Illinois waters of Lake Michigan), Michigan and Ontaio
    will have multiple juristictions (one for each lake they have in
    their pervue(??))

    A geom will be used to capture the outline of the juristiction
    within the great lake shoreline, but extends will be updated to
    include stocking events in tributatries so that map widgets can be
    appropriately zoomed so that events aren't clipped.

    """

    lake = models.ForeignKey(Lake, default=1, on_delete=models.CASCADE)
    stateprov = models.ForeignKey(StateProvince, default=1, on_delete=models.CASCADE)

    slug = models.CharField(max_length=5, unique=True)
    name = models.CharField(max_length=30, unique=True)
    description = models.CharField(max_length=300)
    color = ColorField(default="#FF0000")
    # complete geometry of shoreline and state/province boundaries
    geom = models.MultiPolygonField(srid=4326, blank=True, null=True)
    # juristiction including associated watersheds
    # geom_plus = models.MultiPolygonField(srid=4326, blank=True, null=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        """String representation for a State."""
        return "{} - {} waters".format(self.lake.lake_name, self.stateprov.name)

    def save(self, *args, **kwargs):
        """
        Populate slug when we save the object.
        """
        # if not self.slug:
        self.slug = slugify("_".join([self.lake.abbrev, self.stateprov.abbrev]))

        super(Jurisdiction, self).save(*args, **kwargs)

    @property
    def centroid():
        """Return the centroid for this grid - used by the serializer."""
        if self.geom:

fsdviz/templates/stocking/_refine_annual_totals_sidebar.html
{% load fsdviz_tags %}
{% load humanize %}

<h5>Refine By</h5>

<div class="ui styled fluid accordion">

    <div class="title">
        <i class="dropdown icon"></i>
        Years
    </div>
    <div class="content">
        <form class="ui mini form" id="years" action="{{request.get_full_path}}" method="get">

            <div class="field">
                <input type="text"  id="first-year" name="first_year" placeholder =
                             "first year">
            </div>
            <div class="field">
                <input type="text"  id="last-year" name="last_year" placeholder =
                             "last year">
            </div>
            <div class="ui hidden divider"></div>
            <button class="mini ui blue button" type="button" onClick=updateYearsClick()>
                Update years
            </button>
        </form>

    </div>


    <div class="title">
        <i class="dropdown icon"></i>
        Lakes
    </div>
    <div class="content">
        <div class="list" id="filter_lake_list">
            {% for item in lake_list %}
                <div class="item">
                    <div class="ui tiny checkbox">
                        <input type="checkbox" name="lake" {% if item.3 %}checked{% endif%}  value="{{item.0}}">
                        <label>
                            {{item.1}} ({{item.0}}) (N={{item.2 | intcomma}})
                        </label>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="ui hidden divider"></div>
        <button class="mini ui blue button" type="button" onClick=updateLakeClick()>
            Update Lakes
        </button>

    </div>


    <div class="title">
        <i class="dropdown icon"></i>
        States/Province
    </div>
    <div class="content">
        <div class="list" id="filter_stateprov_list">
            {% for item in stateprov_list %}

                <div class="item">
                    <div class="ui tiny checkbox" data-tooltip="{{item.1}}" data-position="right center">
                        <input type="checkbox" name="stateprov" {% if item.3 %}checked{% endif%} value="{{item.0}}">
                        <label>
                            {{item.0}} (N={{item.2  | intcomma}})
                        </label>
                    </div>
                </div>

            {% endfor %}
        </div>
        <div class="ui hidden divider"></div>
        <button class="mini ui blue button" type="button" onClick=updateStateProvClick()>
            Update States/Province
        </button>

    </div>



    <div class="title">
        <i class="dropdown icon"></i>
        Agencies
    </div>
    <div class="content">
        <div class="list" id="filter_agency_list">
            {% for item in agency_list %}

                <div class="item" data-tooltip="{{item.1}}" data-position="right center">
                    <div class="ui tiny checkbox">
                        <input title="Agency Full Name" type="checkbox" {% if item.3 %}checked{% endif%} name="agency" value="{{item.0}}">
                        <label>
                            {{item.0}} (N={{item.2  | intcomma}})
                        </label>
                    </div>
                </div>

            {% endfor %}
        </div>
        <div class="ui hidden divider"></div>
        <button class="mini ui blue button" type="button" onClick=updateAgenciesClick()>
            Update Agencies
        </button>
    </div>

</div>

fsdviz/templates/stocking/_refine_upload_events_sidebar.html
{% load fsdviz_tags %}
{% load humanize %}


<h5>Refine By</h5>

<div class="ui styled fluid accordion">

    <div class="title">
        <i class="dropdown icon"></i>
        Years
    </div>
    <div class="content">
        <div class="list" id="filter_year_list">
            {% for item in year_list %}
                <div class="item">
                    <div class="ui tiny checkbox">
                        <input type="checkbox" name="year" {% if item.3 %}checked{% endif%}  value="{{item.0}}">
                        <label>
                            {{item.1}} (N={{item.2 | intcomma}})
                        </label>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="ui hidden divider"></div>
        <button class="mini ui blue button" type="button" onClick=updateYearsClick()>
            Update Years
        </button>

    </div>

    <div class="title">
        <i class="dropdown icon"></i>
        Lakes
    </div>
    <div class="content">
        <div class="list" id="filter_lake_list">
            {% for item in lake_list %}
                <div class="item">
                    <div class="ui tiny checkbox">
                        <input type="checkbox" name="lake" {% if item.3 %}checked{% endif%}  value="{{item.0}}">
                        <label>
                            {{item.1}} ({{item.0}}) (N={{item.2 | intcomma}})
                        </label>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="ui hidden divider"></div>
        <button class="mini ui blue button" type="button" onClick=updateLakeClick()>
            Update Lakes
        </button>

    </div>



    <div class="title">
        <i class="dropdown icon"></i>
        Agencies
    </div>
    <div class="content">
        <div class="list" id="filter_agency_list">
            {% for item in agency_list %}

                <div class="item" data-tooltip="{{item.1}}" data-position="right center">
                    <div class="ui tiny checkbox">
                        <input title="Agency Full Name" type="checkbox" {% if item.3 %}checked{% endif%} name="agency" value="{{item.0}}">
                        <label>
                            {{item.0}} (N={{item.2  | intcomma}})
                        </label>
                    </div>
                </div>

            {% endfor %}
        </div>
        <div class="ui hidden divider"></div>
        <button class="mini ui blue button" type="button" onClick=updateAgenciesClick()>
            Update Agencies
        </button>
    </div>


</div>

fsdviz/templates/stocking/upload_event_detail.html
{% extends 'fsdviz_base.html' %}
{% load humanize %}
{% load fsdviz_tags %}
{% load static %}
{% load tz %}

{% block extra_head %}


    <style media="screen">
     .small {
         font-size: 0.8rem;
     }

     .active-marker {
         stroke: black;
         stroke-opacity: 1.0;
         fill-opacity: 1.0;
     }

     #stocking-events {
         min-height: 500px;
     }

    </style>

    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.5.1/dist/leaflet.css" >
    <script src= "https://unpkg.com/leaflet@1.5.1/dist/leaflet-src.js"></script>


{% endblock %}

{% block title %} Upload Event Detail {% endblock title %}


{% block content %}

    <div class="ui container" id="content">

        <div  class="ui grid"  >
            <div class="six wide column">


                {% if messages %}
                    {% for message in messages %}
                        <div class="ui
                                    {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %} success {% else %} negative {% endif %}

                                    message">
                            <p> {{ message }} </p>
                        </div>
                    {% endfor %}
                {% endif %}


                <h1 class="ui huge header">Data Upload Event Details</h1>

                <div class="ui grid">
                    <div class="ui row">
                        <div class="eight wide column">
                            <a class="tiny ui green button"
                               href="{% url 'stocking:data-upload-event-list' %}">
                                Return to Upload Event List
                            </a>
                        </div>
                        <div class="eight wide right aligned column">
                            <a class="tiny ui blue button"
                               href="{% url 'stocking:upload-stocking-events' %}">
                                Upload More Events
                            </a>
                        </div>
                    </div>
                </div>


                <table class="ui definition table">
                    <tbody>
                        <tr>
                            <td>Uploaded By:</td>
                            <td>{{object.uploaded_by.first_name}} {{ object.uploaded_by.last_name }}</td>
                        </tr>
                        <tr>
                            <td>Uploaded On:</td>
                            <td>{{ object.timestamp|timezone:"America/Detroit" }} (EST)</td>
                        </tr>
                        <tr>
                            <td>Agency:</td>
                            <td>{{ object.agency }}</td>
                        </tr>
                        <tr>
                            <td>Lake:</td>
                            <td>{{ object.lake }}</td>
                        </tr>

                        <tr>
                            <td>Comment:</td>
                            <td>{{ object.comment |default:"No comment provided."}}</td>
                        </tr>

                    </tbody>
                </table>

                <div class="ui fluid card">
                    <div class="content">
                        <div class="header">Legend</div>
                    </div>
                    <div class="content">

                        <div id="legend-table">
                            <div class="ui medium header"
                                id="category-value-label">Species</div>
                            <table
                                class="ui celled compact table tablesorter"
                                style="font-size: 0.7em"
                            >
                                <tbody id="legend-table-tbody"></tbody>
                            </table>
                        </div>
                    </div>
                </div>


            </div>
            <div  class="ten wide column" >
                <div class="ui segment">

                    <div id="mapid" style='width: 700px; height: 700px;'></div>

                </div>
            </div>

            <div class="ui row" id="stocking-events">

                <div class="ui  basic segment">

                    <h4>Stocking Events</h4>

                    {% if events %}
                        <table class="ui compact single line celled table tablesorter" style="font-size: 0.9em">
                            <thead>
                                <tr>
                                    <th scope="col">Stock ID</th>
                                    <th scope="col">Agency Stock ID</th>
                                    <th scope="col">Stocking Site</th>
                                    <th scope="col" data-sorter="shortDate" data-date-format="MMM-dd-yy">Date</th>
                                    <th scope="col">Species</th>
                                    <th scope="col">Strain</th>
                                    <th scope="col">Year Class</th>
                                    <th scope="col">Life Stage</th>
                                    <th scope="col">Stocking Method</th>
                                    <th scope="col">Clip</th>
                                    <th scope="col">Mark</th>
                                    <th scope="col">Yr.Eq.</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for event in events %}
                                    <tr data-coord="{{event.geom_lat}}; {{ event.geom_lon }}" >
                                        <td> <a href="{% url 'stocking:stocking-event-detail' event.stock_id %}">{{ event.stock_id }}</a></td>
                                        <td> {{ event.agency_stock_id|default:"---" }}</td>
                                        <td title="{{ event.site }}"> {{ event.site }}</td>
                                        <td> {{ event.date|date:"M-d-y" }}</td>
                                        <td> {{ event.species.common_name | title}}</td>
                                        <td> {{ event.strain_alias.strain.strain_label }}</td>
                                        <td> {{ event.year_class }}</td>
                                        <td> {{ event.lifestage.description | title }}</td>
                                        <td> {{ event.stocking_method.description | title }}</td>
                                        <td> {{ event.clip_code.clip_code|default:"---"}}</td>
                                        <td> {{ event.mark|default:"---"}}</td>
                                        <td> {{ event.yreq_stocked | intcomma }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>


                    {% else %}
                        <h5>
                            oops - no stocking events appear to be related with this upload event.
                        </h5>
                    {% endif %}

                </div>
            </div>
        </div>

    </div>

{% endblock %}


{% block extra_js%}

    {% include "_table_sorter.html" %}

    {{ object.lake.coordinate_limits|json_script:"map-bounds" }}

    <script>
     const dataURL = "{% url 'api:api-stocking-event-upload-map' object.slug %}";
    </script>

    <script src="{% static "js/upload_event_detail.js" %}"></script>


{% endblock %}