config/urls.py
"""fsdviz URL Configuration
"""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from django.contrib.flatpages import views as flatpage_views
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from fsdviz.myusers.views import account_redirect

# our homepage:  TEMP!!
from fsdviz.stocking.views import PieChartMapViewLastYear
from rest_framework.documentation import include_docs_urls
from rest_framework.permissions import AllowAny


from fsdviz.common.api.views import (
    AgencyViewSet,
    SpeciesViewSet,
    JurisdictionViewSet,
    StateProvinceViewSet,
    LakeViewSet,
    ManagementUnitViewSet,
    StrainSpeciesViewSet,
    StrainAliasViewSet,
    Grid10ViewSet,
    LatLonFlagViewSet,
    MarkViewSet,
)

from fsdviz.stocking.api.views import (
    LifeStageViewSet,
    YearlingEquivalentViewSet,
    StockingMortalityViewSet,
    StockingMethodViewSet,
    StockingEventViewSet,
    CWTEventListAPIView,
)


API_TITLE = "Great Lakes Fish Stocking API"
API_DESCRIPTION = "A web API for Great Lakes Fish Stocking Database"


public_urls = [
    path("api/v1/common/lake", LakeViewSet.as_view({"get": "list"})),
    path("api/v1/common/agency", AgencyViewSet.as_view({"get": "list"})),
    path("api/v1/common/jurisdiction", JurisdictionViewSet.as_view({"get": "list"})),
    path(
        "api/v1/common/management_unit", ManagementUnitViewSet.as_view({"get": "list"})
    ),
    path("api/v1/common/state_province", StateProvinceViewSet.as_view({"get": "list"})),
    path("api/v1/common/grid10", Grid10ViewSet.as_view({"get": "list"})),
    path("api/v1/common/latlonflag", LatLonFlagViewSet.as_view({"get": "list"})),
    path("api/v1/common/mark", MarkViewSet.as_view({"get": "list"})),
    path("api/v1/common/species", SpeciesViewSet.as_view({"get": "list"})),
    path("api/v1/common/strain", StrainSpeciesViewSet.as_view({"get": "list"})),
    path("api/v1/common/strain_alias", StrainAliasViewSet.as_view({"get": "list"})),
    path("api/v1/stocking/lifestage", LifeStageViewSet.as_view({"get": "list"})),
    path(
        "api/v1/stocking/yearling_equivalent",
        YearlingEquivalentViewSet.as_view({"get": "list"}),
    ),
    path("api/v1/stocking/stocking_mortality", StockingMortalityViewSet.as_view({"get": "list"})),
    path(
        "api/v1/stocking/stocking_method",
        StockingMethodViewSet.as_view({"get": "list"}),
    ),
    path("api/v1/stocking/events", StockingEventViewSet.as_view({"get": "list"})),
    path("api/v1/stocking/get_cwt_events", CWTEventListAPIView.as_view()),
]

schema_view = get_schema_view(
    openapi.Info(
        title=API_TITLE,
        default_version="v1",
        description=API_DESCRIPTION,
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="adam.cottrill@ontario.ca"),
        license=openapi.License(name="BSD License"),
    ),
    # generate docs for all endpoint from here down:
    # patterns=urlpatterns + common_api_urls + stocking_api_urls,
    patterns=public_urls,
    public=True,
    permission_classes=(AllowAny,),
)


urlpatterns = [
    path("coregonusclupeaformis/doc/", include("django.contrib.admindocs.urls")),
    path("coregonusclupeaformis/", admin.site.urls),
    path("login/", account_redirect, name="account-redirect"),
    path("users/", include("fsdviz.myusers.urls")),
    path("users/", include("django.contrib.auth.urls")),
    path(
        "about/",
        flatpage_views.flatpage,
        {"url": "/about/"},
        name="about",
    ),
    path("pages/", include("django.contrib.flatpages.urls")),
    path("shared/", include("fsdviz.common.urls", namespace="common")),
    path("stocking/", include("fsdviz.stocking.urls", namespace="stocking")),
    path("resource_library/", include("resource_library.urls", "resource_library")),
    # path("cwt/", include("cwt.urls")),
    # API's
    path("tickets/", include(("tickets.urls", "tickets"), namespace="tickets")),
    path("api-auth/", include("rest_framework.urls")),

    path("api/v1/common/", include("fsdviz.common.api.urls", namespace="common_api")),
    path(
        "api/v1/stocking/",
        include("fsdviz.stocking.api.urls", namespace="stocking_api"),
    ),
    path("bookmarks/", include("bookmark_it.urls")),
    # =============================================
    #          API AND DOCUMENTATION
    path(
        "api/v1/public_urls/",
        schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),
    # api documentation
    re_path(
        r"^api/v1/swagger(?P<format>\.json|\.yaml)$",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "api/v1/swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("", PieChartMapViewLastYear, name="home"),
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = (
        [
            path("__debug__/", include(debug_toolbar.urls)),
        ]
        + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
        + urlpatterns
    )

fsdviz/common/urls.py
from django.urls import path

from .views import lookup_tables, spatial_lookup

app_name = "common"

urlpatterns = [
    path("spatial_lookup/", spatial_lookup, name="spatial-lookup"),
    path("lookup_tables/", lookup_tables, name="lookup-tables"),
]

fsdviz/myusers/urls.py
"""urls for our custom user app."""

from django.urls import path
from . import views

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup')
]

fsdviz/stocking/urls.py
from django.urls import path

from .views import (
    PieChartMapView,
    PieChartMapViewLastYear,
    StockingEventListView,
    StockingEventDetailView,
    StockingAnnualTotalsListView,
    find_events,
    filtered_events,
    upload_events,
    xls_events,
    edit_stocking_event,
    DataUploadEventListView,
    DataUploadEventDetailView,
    CWTListView,
    CWTSequenceDetail,
    find_cwt_events,
    filtered_cwt_events,
)

app_name = "stocking"

urlpatterns = [
    path("", PieChartMapViewLastYear, name="stocking-events"),
    path("find_events/", find_events, name="find-stocking-events"),
    path("filtered_events/", filtered_events, name="filtered-stocking-events"),
    path("events/<int:year>/", PieChartMapView.as_view(), name="stocking-events-year"),
    # the default events view will be to return the most recent year
    # for all lakes:
    path("events/", PieChartMapViewLastYear, name="stocking-events-latest-year"),
    # stocking event lists
    path(
        "events_list/",
        StockingEventListView.as_view(),
        name="stocking-event-list",
    ),
    path(
        "event_detail/<stock_id>/",
        StockingEventDetailView.as_view(),
        name="stocking-event-detail",
    ),
    path(
        "annual_totals/",
        StockingAnnualTotalsListView.as_view(),
        name="annual-totals-list",
    ),
    path("edit_event/<stock_id>/", edit_stocking_event, name="edit-stocking-event"),
    path("upload_events/", upload_events, name="upload-stocking-events"),
    path("uploaded_events/", xls_events, name="xls-events-form"),
    path(
        "data_upload_events/",
        DataUploadEventListView.as_view(),
        name="data-upload-event-list",
    ),
    path(
        "data_upload_event_detail/<slug>/",
        DataUploadEventDetailView.as_view(),
        name="data-upload-event-detail",
    ),
    path("cwts/", CWTListView.as_view(), name="cwt-list"),
    path(
        "cwt_detail/<str:cwt_number>/", CWTSequenceDetail.as_view(), name="cwt-detail"
    ),
    path("find_cwt_events/", find_cwt_events, name="find-cwt-stocking-events"),
    path(
        "filtered_cwt_events/", filtered_cwt_events, name="filtered-cwt-stocking-events"
    ),
]

fsdviz/common/api/views.py
"""Views for the api for our common models

The veiws in this file should all be publicly available as readonly.
"""


from django.contrib.gis.db.models.functions import Distance
from django.db.models import F
from fsdviz.common.filters import (
    Grid10Filter,
    JurisdictionFilter,
    ManagementUnitFilter,
    MarkFilter,
    StateProvinceFilter,
    StrainFilter,
    StrainAliasFilter,
)
from fsdviz.common.models import (
    CWT,
    Agency,
    CompositeFinClip,
    FishTag,
    Grid10,
    Jurisdiction,
    Lake,
    LatLonFlag,
    ManagementUnit,
    Mark,
    PhysChemMark,
    Species,
    StateProvince,
    Strain,
    StrainAlias,
)
from fsdviz.common.utils import get_polygons, parse_geom
from rest_framework import status, viewsets
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny, IsAuthenticatedOrReadOnly
from rest_framework.response import Response
from rest_framework.views import APIView

from .serializers import (
    AgencySerializer,
    CompositeFinClipSerializer,
    CWTSerializer,
    FishTagSerializer,
    Grid10Serializer,
    JurisdictionSerializer,
    LakeSerializer,
    LatLonFlagSerializer,
    ManagementUnitSerializer,
    MarkSerializer,
    PhysChemMarkSerializer,
    SpeciesSerializer,
    StateProvinceSerializer,
    StrainAliasSerializer,
    StrainSpeciesSerializer,
)


class AgencyViewSet(viewsets.ReadOnlyModelViewSet):

    permission_classes = (IsAuthenticatedOrReadOnly,)
    queryset = Agency.objects.all()
    serializer_class = AgencySerializer
    lookup_field = "abbrev"


class CompositeFinClipViewSet(viewsets.ReadOnlyModelViewSet):

    permission_classes = (IsAuthenticatedOrReadOnly,)
    queryset = CompositeFinClip.objects.all()
    serializer_class = CompositeFinClipSerializer
    lookup_field = "clip_code"


class FishTagViewSet(viewsets.ReadOnlyModelViewSet):

    permission_classes = (IsAuthenticatedOrReadOnly,)
    queryset = FishTag.objects.all()
    serializer_class = FishTagSerializer
    lookup_field = "tag_code"


class PhysChemMarkViewSet(viewsets.ReadOnlyModelViewSet):

    permission_classes = (IsAuthenticatedOrReadOnly,)
    queryset = PhysChemMark.objects.all()
    serializer_class = PhysChemMarkSerializer
    lookup_field = "mark_code"


@api_view(["POST"])
@permission_classes([AllowAny])
def roi_spatial_attrs(request):
    """This function accepts post requests that contain a geojson
    representation of a polygon and returns a dictionary containing
    the basic elements needed to validate the find-events forms and
    limit the choices in the drop-downs for spatial fields to the
    enties that overlap with the roi.  (if the region of interest in
    entirely within lake michigan - there is no point in including the
    aother lakes, or their children in the select widget).

    Given a valid polygon geometry, return a dictionary with the following elements:

    + lakes - list of lakes with id, lake name, lake abbrev

    + juristictions - list of jurisdictions with id, stateprov name, stateprov abbrev

    + manUnits - list of management units including the slug,
      management unit type, and wether or not it should be considered to
      be a primary management unit.

    post data should contain a json string of the form:

    {"roi":
    "POLYGON ((-80.98 45.03, -81.15 44.90, -81.02 44.42, -80.38 44.45, -80.33 44.85, -80.98 45.03))"
    }

    """

    roi = parse_geom(request.data.get("roi"))

    if roi is None:
        return Response({}, status=status.HTTP_400_BAD_REQUEST)

    ret = dict()

    lakes = Lake.objects.filter(geom__intersects=roi).values(
        "id", "abbrev", "lake_name"
    )

    if lakes:
        ret["lakes"] = list(lakes)
    else:
        ret["lakes"] = ""

    jurisdictions = (
        Jurisdiction.objects.select_related("lake", "stateprov")
        .filter(geom__intersects=roi)
        .values(
            # jurisdiction attributes
            "id",
            "lake_id",
            "stateprov_id",
            jurisd=F("slug"),
            jurisdiction_name=F("name"),
            # centroid=F("geom__centroid__wkt"),
            # lake attributes:
            lake_abbrev=F("lake__abbrev"),
            lake_name=F("lake__lake_name"),
            # state prov__ attributes:
            stateprov_abbrev=F("stateprov__abbrev"),
            stateprov_name=F("stateprov__name"),
        )
    )

    if jurisdictions:
        ret["jurisdictions"] = list(jurisdictions)

    else:
        ret["jurisdictions"] = ""

    # get our stat disctricts too. for now just return the slugs
    man_units = (
        ManagementUnit.objects.filter(geom__intersects=roi)
        .filter(primary=True)
        .values("slug", "mu_type", "primary")
    )

    if man_units:
        ret["manUnits"] = list(man_units)
    else:
        ret["manUnits"] = ""

    return Response(ret, status=status.HTTP_200_OK)


@api_view(["POST"])
@permission_classes([AllowAny])
def pt_spatial_attrs(request):
    """This function accepts post requests that contain a geojson
    representation of a point and returns a dictionary containing the
    basic elements needed to validate the spatial widgets in the
    stocking event and stocking upload forms.  Given a lat-lon, return
    a dictionary with the following elements:

    + lake - with id, lake name, lake abbrev
    + juristiction - with id, stateprov name, stateprov abbrev
    + manUnit - id, label
    + grid10 - id, label, lake abbrev.

    post data should contain a json string of the form:

    {"point": "POINT(-81.5 44.5)"}


    """

    pt = parse_geom(request.data.get("point"))
    if pt is None:
        return Response({}, status=status.HTTP_400_BAD_REQUEST)

    polygons = get_polygons(pt)

    return Response(polygons, status=status.HTTP_200_OK)


@api_view(["POST"])
@permission_classes([AllowAny])
def get_lake_from_pt(request):
    """This function accepts post requests that contain a geojson
    representation of a point.  The view returns a dictionary contianing
    the id, abbreviation, name, centroid and bounds (extent) of the lake
    containing the point, or an empty dictionary if the dat is not geojson
    or falls outside of any lake.

    TODO: add options for 'pure' and 'plus' geometries

    """

    geom = request.query_params.get("geom")
    pt = parse_geom(request.data.get("point"))
    if pt is None:
        return Response({}, status=status.HTTP_400_BAD_REQUEST)

    lake = Lake.objects.filter(geom__contains=pt).first()

    if lake:
        ret = dict(
            id=lake.id,
            abbrev=lake.abbrev,
            lake_name=lake.lake_name,
            centroid=lake.geom.centroid.wkt,
            extent=lake.geom.extent,
        )

        if geom == "geom":
            ret["geom"] = lake.geom.geojson

        return Response(ret, status=status.HTTP_200_OK)
    else:
        # no lake object could be associated with that point.
        # 400
        return Response({}, status=status.HTTP_404_NOT_FOUND)


@api_view(["POST"])
@permission_classes([AllowAny])
def get_jurisdiction_from_pt(request):
    """This function accepts post requests that contain a geojson
    representation of a point.  The view returns a dictionary contianing
    the id, abbreviation, name, centroid and bounds (extent) of the jurisdiction
    containing the point, or an empty dictionary if the dat is not geojson
    or falls outside of any jurisdiction.

    TODO: add options for 'pure' and 'plus' geometries

    """

    geom = request.query_params.get("geom")
    pt = parse_geom(request.data.get("point"))
    if pt is None:
        return Response({}, status=status.HTTP_400_BAD_REQUEST)

    jurisdiction = (
        Jurisdiction.objects.select_related("lake", "stateprov")
        .filter(geom__contains=pt)
        .first()
    )

    if jurisdiction:
        ret = dict(
            id=jurisdiction.id,
            # lake attributes:
            lake_id=jurisdiction.lake.id,
            lake_abbrev=jurisdiction.lake.abbrev,
            lake_name=jurisdiction.lake.lake_name,
            # state prov. attributes:
            stateprov_id=jurisdiction.stateprov.id,
            stateprov_abbrev=jurisdiction.stateprov.abbrev,
            stateprov_name=jurisdiction.stateprov.name,
            # jurisdiction attributes
            jurisdiction_name=jurisdiction.name,
            centroid=jurisdiction.geom.centroid.wkt,
            extent=jurisdiction.geom.extent,
        )

        if geom == "geom":
            ret["geom"] = jurisdiction.geom.geojson

        return Response(ret, status=status.HTTP_200_OK)
    else:
        # no jurisdiction object could be associated with that point.
        # 400
        return Response({}, status=status.HTTP_404_NOT_FOUND)


def manUnit_dict(obj, geom=None):
    """Serialize a management unit to a python dictionary

    Arguments:
    - `obj`: a ManagementUnit instance
    """

    item = dict(
        id=obj.id,
        slug=obj.slug,
        label=obj.label,
        mu_type=obj.mu_type,
        centroid=obj.geom.centroid.wkt,
        extent=obj.geom.extent,
    )

    if geom == "geom":
        item["geom"] = obj.geom.geojson

    return item


@api_view(["POST"])
@permission_classes([AllowAny])
def get_management_unit_from_pt(request):
    """This function accepts post requests that contains a geojson
    representation of a point.  The view returns a dictionary contianing
    the id, label, mu_type, centroid and bounds (extent) of the management_unit
    containing the point, or an empty dictionary if the data is not geojson
    or falls outside of any management_unit.

    This function takes an additional argument (mu_type) as a query
    parameter that controls what type of managemnet unit is returned -
    current options are stat_dist, mu, qma, ltrz.  Others could be
    added in the future.  If the mu_type argument is not included in

fsdviz/recovery/views.py
from django.shortcuts import render

# Create your views here.

fsdviz/templates/_paginator.html
{% if is_paginated %}
    {% load i18n %}
    {% load fsdviz_tags %}

    <div class="ui pagination menu"  style="margin-top:10px">

        {% if page_obj.has_previous %}

            <a class="item" aria-label="Go to previous page" href="?page={{ page_obj.previous_page_number }}{% for key,value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">Previous</a>

        {% else %}

            <a class="item disabled" aria-label="Go to previous page is disabled. You are on the first page.">Previous</a>

        {% endif %}

        {% get_adjusted_elided_page_range paginator page_obj.number as page_range %}
        {% for i in page_range %}
            {% if i == page_obj.paginator.ELLIPSIS %}

                <a class="item">{{ i }}</a>

            {% elif i == page_obj.number %}

                <a class="active item" href="?page={{ i }}{% for key,value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">
                    {{ i }} of {{ paginator.num_pages }}
                </a>

            {% else %}

                <a class="item" aria-label="Go to page {{ i }}" href="?page={{ i }}{% for key,value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">{{ i }}
                </a>

            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="item" aria-label="Go to next page" href="?page={{ page_obj.next_page_number }}{% for key,value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">Next</a>
        {% else %}

            <a class="item disabled" aria-label="Go to next page is disabled. You are on the last page." disabled="disabled">Next</a>

        {% endif %}

    </div>
{% endif %}

fsdviz/templates/_table_sorter.html
    <!-- tablesorter plugin-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.17.7/js/jquery.tablesorter.js"></script>

    <!-- tablesorter widget file - loaded after the plugin -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.17.7/js/jquery.tablesorter.widgets.js"></script>

    <script>

     $(".tablesorter").tablesorter({
         theme: "bootstrap",
         widthFixed: true,
         showProcessing: true,
         headerTemplate: "{content} {icon}",
         widgets: ["zebra", "uitheme", "scroller"],
         widgetOptions: {
             scroller_height: 300,
             scroller_barWidth: 17,
             scroller_jumpToHeader: true,
             scroller_idPrefix: "s_",
         },
     });
    </script>

fsdviz/templates/fsdviz_base.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="stylesheet" href="https://unpkg.com/fomantic-ui@2.8.3/dist/semantic.min.css">

        <script src="{% static "bookmark_modal_form.js" %}"></script>


        <style media="screen">


         body {
             min-width: 100%;
         }

         .container{
             position: relative;
             min-height: 100vh;
         }

         .footer {
             position: absolute;
             bottom: 0;
             width: 100%;
             height: 75px;
         }


         .ui.grid {
             margin-top: .2rem;
         }
         .ui.dropdown .menu { z-index: 999999 !important; }



        </style>


        {% block extra_head %}

        {% endblock extra_head%}

        <title>{% block title %} GLFS DataViz {% endblock title %} </title>


        {% if not debug %}
            <!-- Google tag (gtag.js) -->
            <script async src="https://www.googletagmanager.com/gtag/js?id=G-BR59QP377W"></script>
            <script>
             window.dataLayer = window.dataLayer || [];
             function gtag(){dataLayer.push(arguments);}
             gtag('js', new Date());

             gtag('config', 'G-BR59QP377W');
            </script>
            {% endif %}

    </head>
    <body>

        <div class="container">

            {% block navbar %}

                <div class="ui top attached menu">
                    <a class="item" href="{% url 'home' %}" >
                        <span class="ui large text"><b>Great Lakes Fish Stocking</b></span>
                    </a>
                    <div class="ui dropdown icon item">
                        Stocking
                        <div class="menu">
                            <div class="item">
                                <a href="{% url 'stocking:stocking-event-list' %}">Events List</a>
                            </div>
                            <div class="item">
                                <a href="{% url 'stocking:find-stocking-events' %}">Find Events</a>
                            </div>
                            <div class="item">
                                <a href="{% url 'stocking:annual-totals-list' %}">Annual Totals</a>
                            </div>

                        </div>
                    </div>
                    <div class="ui dropdown icon item">
                        CWT
                        <div class="menu">
                            <div class="item">
                                <a href="{% url 'stocking:cwt-list' %}">CWT List</a>
                            </div>
                            <div class="item">
                                <span class="text">
                                    <a href="{% url 'stocking:find-cwt-stocking-events' %}">Find CWT Events</a>
                                </span>
                            </div>
                        </div>
                    </div>

                    <div class="ui dropdown icon item">
                        Utilities
                        <div class="menu">
                            {% if user.role == 'asc' or user.role == 'glsc' %}
                                <div class="item"><a href="{% url 'stocking:data-upload-event-list' %}" >Data Upload List</a></div>
                                <div class="item"><a href="{% url 'stocking:upload-stocking-events' %}" >Upload Data</a></div>
                                <div class="ui divider"></div>
                            {% endif %}
                            <div class="item"><a href="{% url 'common:spatial-lookup' %}" >Spatial Lookup</a></div>
                            <div class="item"><a href="{% url 'common:lookup-tables' %}" >Lookup Tables</a></div>
                            <div class="item"><a href="{% url 'resource_library:resource_list' %}" >Reference Material</a></div>
                            {% if user.is_authenticated %}
                                <div class="ui divider"></div>
                                {% block create_bookmark %}
                                    <div class="item"><a href="{% url 'bookmark_it:bookmark_modal' %}" onClick="openNewBookmarkModal(event); return false;">Create Bookmark Here</a></div>
                                {% endblock create_bookmark %}

                                <div class="item"><a href="{% url 'bookmark_it:bookmark_list' %}">Bookmarks List</a></div>
                            {% endif %}
                        </div>
                    </div>

                    <a class="item" href="{% url 'about' %}">
                        About
                    </a>

                    {% if user.is_authenticated %}

                        <div class="ui dropdown icon item">
                            Admin
                            <div class="menu">
                                <div class="item"><a href="{% url 'password_change' %}">Change Your Password</a></div>
                                {% if user.is_staff %}
                                    <div class="item"><a href="{% url 'admin:index' %}" >Django Admin</a></div>
                                {% endif %}
                                <div class="ui divider"></div>

                                <div class="item"><a href="{% url 'tickets:ticket_list' %}">TicketTracker</a></div>

                                <div class="ui divider"></div>
                                <div class="item"><a href="{% url 'logout' %}">Logout</a></div>

                            </div>
                        </div>


                        <div class="ui dropdown icon item" id="welcome">

                            Welcome {{ user.first_name }}!

                        </div>

                    {% else %}

                        <div class="ui item" id="login">

                            <a href="{% url 'login' %}">Login</a>

                        </div>


                    {% endif %}


                    {% block navbar_search %}


                        <div class="right menu">
                            <form id="menu-search-form" class="item" action="{% url 'stocking:stocking-event-list' %}" method="get">
                                <div class="ui right aligned category search item">
                                    <div class="ui transparent icon input">
                                        <input class="prompt" type="text" required placeholder="Search By Event id..." name="q">
                                        <i id="menu-search-icon" class="search link icon"></i>
                                    </div>
                                </div>
                            </form>
                        </div>


                    {% endblock navbar_search %}

                </div>

            {% endblock navbar%}


            {% block messages %}

                <div id="unsupported-browser" class="ui hidden negative icon message">
                    <i class="exclamation circle icon"></i>
                    <i class="close icon"></i>
                    <div class="content">
                        <div class="header">
                            Unsupported Browser!
                        </div>
                        <p>
                            This website will offer limited functionality
                            in this browser. The mapping and interactive
                            graphics on this website require a more recent
                            version of major browsers like Chrome,
                            Firefox, Safari, and Edge in order to render
                            properly.
                        </p>
                    </div>
                </div>

            {% endblock %}

            <div class="ui basic segment">

            </div>


            {% block content %}

            {% endblock content%}


            {% block footer %}

                <div class="ui segment footer">

                    <img class="ui medium  image"
                         alt="Great Lakes Fisheries Commision - Science Transfer Logo"
                         src="{% static 'GLFC-Science-Transfer.png'%}">
                </div>
            {% endblock footer %}


        </div>  <!-- main container -->

        <script src="https://code.jquery.com/jquery-3.3.1.min.js"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
                crossorigin="anonymous"></script>

            <script src="https://unpkg.com/fomantic-ui@2.8.3/dist/semantic.min.js"></script>

            <script>

             function isIE() {
                 return /Trident\/|MSIE/.test(window.navigator.userAgent);
             }

             let showBrowserAlert = (function () {
                 let message = document.getElementById('unsupported-browser');
                 let is_IE = isIE();
                 if (is_IE) {
                     message.classList.remove("hidden");
                 }
             });

             document.addEventListener('DOMContentLoaded', showBrowserAlert);

             $(document).ready(function() {

                 $('.ui.accordion')
                     .accordion();

                 $('.ui.dropdown')
                     .dropdown();

                 $('.message .close')
                     .on('click', function() {
                         $(this)
                             .closest('.message')
                             .transition('fade')
                         ;
                     })
                 ;

             });


             $( "#menu-search-icon" ).click(function(event){
                 event.preventDefault();
                 if ($('#menu-search-form')[0].checkValidity())
                     $('#menu-search-form').submit();
                 else
                     $('#menu-search-form')[0].reportValidity()
             });

            </script>


            {% block bookmark_modal_form %}
                {% include 'bookmark_it/bookmark_modal_form.html' %}
            {% endblock bookmark_modal_form %}


            {% block extra_js %}

            {% endblock extra_js %}

    </body>
</html>